package com.test.mapper;

import com.test.bean.CSUser;
import com.test.bean.CSUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CSUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int countByExample(CSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int deleteByExample(CSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int insert(CSUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int insertSelective(CSUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    List<CSUser> selectByExampleWithBLOBs(CSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    List<CSUser> selectByExample(CSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    CSUser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") CSUser record, @Param("example") CSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") CSUser record, @Param("example") CSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int updateByExample(@Param("record") CSUser record, @Param("example") CSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int updateByPrimaryKeySelective(CSUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CSUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    int updateByPrimaryKey(CSUser record);
}