package cn.com.easypay.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataModeTxnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int countByExample(DataModeTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int deleteByExample(DataModeTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int insert(DataModeTxnInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int insertSelective(DataModeTxnInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    List<DataModeTxnInfoWithBLOBs> selectByExampleWithBLOBs(DataModeTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    List<DataModeTxnInfo> selectByExample(DataModeTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    DataModeTxnInfoWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") DataModeTxnInfoWithBLOBs record, @Param("example") DataModeTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") DataModeTxnInfoWithBLOBs record, @Param("example") DataModeTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int updateByExample(@Param("record") DataModeTxnInfo record, @Param("example") DataModeTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int updateByPrimaryKeySelective(DataModeTxnInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(DataModeTxnInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    int updateByPrimaryKey(DataModeTxnInfo record);
}