package cn.com.easypay.mapper;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DataModeTxnInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public DataModeTxnInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andModeIdIsNull() {
            addCriterion("MODE_ID is null");
            return (Criteria) this;
        }

        public Criteria andModeIdIsNotNull() {
            addCriterion("MODE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModeIdEqualTo(BigDecimal value) {
            addCriterion("MODE_ID =", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdNotEqualTo(BigDecimal value) {
            addCriterion("MODE_ID <>", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdGreaterThan(BigDecimal value) {
            addCriterion("MODE_ID >", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MODE_ID >=", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdLessThan(BigDecimal value) {
            addCriterion("MODE_ID <", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MODE_ID <=", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdIn(List<BigDecimal> values) {
            addCriterion("MODE_ID in", values, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdNotIn(List<BigDecimal> values) {
            addCriterion("MODE_ID not in", values, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MODE_ID between", value1, value2, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MODE_ID not between", value1, value2, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeTypeIsNull() {
            addCriterion("MODE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andModeTypeIsNotNull() {
            addCriterion("MODE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andModeTypeEqualTo(String value) {
            addCriterion("MODE_TYPE =", value, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeNotEqualTo(String value) {
            addCriterion("MODE_TYPE <>", value, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeGreaterThan(String value) {
            addCriterion("MODE_TYPE >", value, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_TYPE >=", value, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeLessThan(String value) {
            addCriterion("MODE_TYPE <", value, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeLessThanOrEqualTo(String value) {
            addCriterion("MODE_TYPE <=", value, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeLike(String value) {
            addCriterion("MODE_TYPE like", value, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeNotLike(String value) {
            addCriterion("MODE_TYPE not like", value, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeIn(List<String> values) {
            addCriterion("MODE_TYPE in", values, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeNotIn(List<String> values) {
            addCriterion("MODE_TYPE not in", values, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeBetween(String value1, String value2) {
            addCriterion("MODE_TYPE between", value1, value2, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeTypeNotBetween(String value1, String value2) {
            addCriterion("MODE_TYPE not between", value1, value2, "modeType");
            return (Criteria) this;
        }

        public Criteria andModeNameIsNull() {
            addCriterion("MODE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andModeNameIsNotNull() {
            addCriterion("MODE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andModeNameEqualTo(String value) {
            addCriterion("MODE_NAME =", value, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameNotEqualTo(String value) {
            addCriterion("MODE_NAME <>", value, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameGreaterThan(String value) {
            addCriterion("MODE_NAME >", value, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_NAME >=", value, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameLessThan(String value) {
            addCriterion("MODE_NAME <", value, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameLessThanOrEqualTo(String value) {
            addCriterion("MODE_NAME <=", value, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameLike(String value) {
            addCriterion("MODE_NAME like", value, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameNotLike(String value) {
            addCriterion("MODE_NAME not like", value, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameIn(List<String> values) {
            addCriterion("MODE_NAME in", values, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameNotIn(List<String> values) {
            addCriterion("MODE_NAME not in", values, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameBetween(String value1, String value2) {
            addCriterion("MODE_NAME between", value1, value2, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeNameNotBetween(String value1, String value2) {
            addCriterion("MODE_NAME not between", value1, value2, "modeName");
            return (Criteria) this;
        }

        public Criteria andModeWeixinIsNull() {
            addCriterion("MODE_WEIXIN is null");
            return (Criteria) this;
        }

        public Criteria andModeWeixinIsNotNull() {
            addCriterion("MODE_WEIXIN is not null");
            return (Criteria) this;
        }

        public Criteria andModeWeixinEqualTo(String value) {
            addCriterion("MODE_WEIXIN =", value, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinNotEqualTo(String value) {
            addCriterion("MODE_WEIXIN <>", value, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinGreaterThan(String value) {
            addCriterion("MODE_WEIXIN >", value, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_WEIXIN >=", value, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinLessThan(String value) {
            addCriterion("MODE_WEIXIN <", value, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinLessThanOrEqualTo(String value) {
            addCriterion("MODE_WEIXIN <=", value, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinLike(String value) {
            addCriterion("MODE_WEIXIN like", value, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinNotLike(String value) {
            addCriterion("MODE_WEIXIN not like", value, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinIn(List<String> values) {
            addCriterion("MODE_WEIXIN in", values, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinNotIn(List<String> values) {
            addCriterion("MODE_WEIXIN not in", values, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinBetween(String value1, String value2) {
            addCriterion("MODE_WEIXIN between", value1, value2, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andModeWeixinNotBetween(String value1, String value2) {
            addCriterion("MODE_WEIXIN not between", value1, value2, "modeWeixin");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeIsNull() {
            addCriterion("NOTICE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeIsNotNull() {
            addCriterion("NOTICE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeEqualTo(String value) {
            addCriterion("NOTICE_TYPE =", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeNotEqualTo(String value) {
            addCriterion("NOTICE_TYPE <>", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeGreaterThan(String value) {
            addCriterion("NOTICE_TYPE >", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("NOTICE_TYPE >=", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeLessThan(String value) {
            addCriterion("NOTICE_TYPE <", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeLessThanOrEqualTo(String value) {
            addCriterion("NOTICE_TYPE <=", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeLike(String value) {
            addCriterion("NOTICE_TYPE like", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeNotLike(String value) {
            addCriterion("NOTICE_TYPE not like", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeIn(List<String> values) {
            addCriterion("NOTICE_TYPE in", values, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeNotIn(List<String> values) {
            addCriterion("NOTICE_TYPE not in", values, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeBetween(String value1, String value2) {
            addCriterion("NOTICE_TYPE between", value1, value2, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeNotBetween(String value1, String value2) {
            addCriterion("NOTICE_TYPE not between", value1, value2, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneIsNull() {
            addCriterion("NOTICE_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneIsNotNull() {
            addCriterion("NOTICE_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneEqualTo(String value) {
            addCriterion("NOTICE_PHONE =", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneNotEqualTo(String value) {
            addCriterion("NOTICE_PHONE <>", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneGreaterThan(String value) {
            addCriterion("NOTICE_PHONE >", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("NOTICE_PHONE >=", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneLessThan(String value) {
            addCriterion("NOTICE_PHONE <", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneLessThanOrEqualTo(String value) {
            addCriterion("NOTICE_PHONE <=", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneLike(String value) {
            addCriterion("NOTICE_PHONE like", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneNotLike(String value) {
            addCriterion("NOTICE_PHONE not like", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneIn(List<String> values) {
            addCriterion("NOTICE_PHONE in", values, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneNotIn(List<String> values) {
            addCriterion("NOTICE_PHONE not in", values, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneBetween(String value1, String value2) {
            addCriterion("NOTICE_PHONE between", value1, value2, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneNotBetween(String value1, String value2) {
            addCriterion("NOTICE_PHONE not between", value1, value2, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailIsNull() {
            addCriterion("NOTICE_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailIsNotNull() {
            addCriterion("NOTICE_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailEqualTo(String value) {
            addCriterion("NOTICE_EMAIL =", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailNotEqualTo(String value) {
            addCriterion("NOTICE_EMAIL <>", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailGreaterThan(String value) {
            addCriterion("NOTICE_EMAIL >", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailGreaterThanOrEqualTo(String value) {
            addCriterion("NOTICE_EMAIL >=", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailLessThan(String value) {
            addCriterion("NOTICE_EMAIL <", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailLessThanOrEqualTo(String value) {
            addCriterion("NOTICE_EMAIL <=", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailLike(String value) {
            addCriterion("NOTICE_EMAIL like", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailNotLike(String value) {
            addCriterion("NOTICE_EMAIL not like", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailIn(List<String> values) {
            addCriterion("NOTICE_EMAIL in", values, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailNotIn(List<String> values) {
            addCriterion("NOTICE_EMAIL not in", values, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailBetween(String value1, String value2) {
            addCriterion("NOTICE_EMAIL between", value1, value2, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailNotBetween(String value1, String value2) {
            addCriterion("NOTICE_EMAIL not between", value1, value2, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeStateIsNull() {
            addCriterion("NOTICE_STATE is null");
            return (Criteria) this;
        }

        public Criteria andNoticeStateIsNotNull() {
            addCriterion("NOTICE_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeStateEqualTo(String value) {
            addCriterion("NOTICE_STATE =", value, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateNotEqualTo(String value) {
            addCriterion("NOTICE_STATE <>", value, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateGreaterThan(String value) {
            addCriterion("NOTICE_STATE >", value, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateGreaterThanOrEqualTo(String value) {
            addCriterion("NOTICE_STATE >=", value, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateLessThan(String value) {
            addCriterion("NOTICE_STATE <", value, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateLessThanOrEqualTo(String value) {
            addCriterion("NOTICE_STATE <=", value, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateLike(String value) {
            addCriterion("NOTICE_STATE like", value, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateNotLike(String value) {
            addCriterion("NOTICE_STATE not like", value, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateIn(List<String> values) {
            addCriterion("NOTICE_STATE in", values, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateNotIn(List<String> values) {
            addCriterion("NOTICE_STATE not in", values, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateBetween(String value1, String value2) {
            addCriterion("NOTICE_STATE between", value1, value2, "noticeState");
            return (Criteria) this;
        }

        public Criteria andNoticeStateNotBetween(String value1, String value2) {
            addCriterion("NOTICE_STATE not between", value1, value2, "noticeState");
            return (Criteria) this;
        }

        public Criteria andSubUseridIsNull() {
            addCriterion("SUB_USERID is null");
            return (Criteria) this;
        }

        public Criteria andSubUseridIsNotNull() {
            addCriterion("SUB_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andSubUseridEqualTo(String value) {
            addCriterion("SUB_USERID =", value, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridNotEqualTo(String value) {
            addCriterion("SUB_USERID <>", value, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridGreaterThan(String value) {
            addCriterion("SUB_USERID >", value, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_USERID >=", value, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridLessThan(String value) {
            addCriterion("SUB_USERID <", value, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridLessThanOrEqualTo(String value) {
            addCriterion("SUB_USERID <=", value, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridLike(String value) {
            addCriterion("SUB_USERID like", value, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridNotLike(String value) {
            addCriterion("SUB_USERID not like", value, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridIn(List<String> values) {
            addCriterion("SUB_USERID in", values, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridNotIn(List<String> values) {
            addCriterion("SUB_USERID not in", values, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridBetween(String value1, String value2) {
            addCriterion("SUB_USERID between", value1, value2, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubUseridNotBetween(String value1, String value2) {
            addCriterion("SUB_USERID not between", value1, value2, "subUserid");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeIsNull() {
            addCriterion("SUB_CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeIsNotNull() {
            addCriterion("SUB_CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeEqualTo(String value) {
            addCriterion("SUB_CREATETIME =", value, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeNotEqualTo(String value) {
            addCriterion("SUB_CREATETIME <>", value, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeGreaterThan(String value) {
            addCriterion("SUB_CREATETIME >", value, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_CREATETIME >=", value, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeLessThan(String value) {
            addCriterion("SUB_CREATETIME <", value, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("SUB_CREATETIME <=", value, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeLike(String value) {
            addCriterion("SUB_CREATETIME like", value, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeNotLike(String value) {
            addCriterion("SUB_CREATETIME not like", value, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeIn(List<String> values) {
            addCriterion("SUB_CREATETIME in", values, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeNotIn(List<String> values) {
            addCriterion("SUB_CREATETIME not in", values, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeBetween(String value1, String value2) {
            addCriterion("SUB_CREATETIME between", value1, value2, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubCreatetimeNotBetween(String value1, String value2) {
            addCriterion("SUB_CREATETIME not between", value1, value2, "subCreatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeIsNull() {
            addCriterion("SUB_UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeIsNotNull() {
            addCriterion("SUB_UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeEqualTo(String value) {
            addCriterion("SUB_UPDATETIME =", value, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeNotEqualTo(String value) {
            addCriterion("SUB_UPDATETIME <>", value, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeGreaterThan(String value) {
            addCriterion("SUB_UPDATETIME >", value, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_UPDATETIME >=", value, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeLessThan(String value) {
            addCriterion("SUB_UPDATETIME <", value, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("SUB_UPDATETIME <=", value, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeLike(String value) {
            addCriterion("SUB_UPDATETIME like", value, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeNotLike(String value) {
            addCriterion("SUB_UPDATETIME not like", value, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeIn(List<String> values) {
            addCriterion("SUB_UPDATETIME in", values, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeNotIn(List<String> values) {
            addCriterion("SUB_UPDATETIME not in", values, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeBetween(String value1, String value2) {
            addCriterion("SUB_UPDATETIME between", value1, value2, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("SUB_UPDATETIME not between", value1, value2, "subUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSubStateIsNull() {
            addCriterion("SUB_STATE is null");
            return (Criteria) this;
        }

        public Criteria andSubStateIsNotNull() {
            addCriterion("SUB_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andSubStateEqualTo(String value) {
            addCriterion("SUB_STATE =", value, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateNotEqualTo(String value) {
            addCriterion("SUB_STATE <>", value, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateGreaterThan(String value) {
            addCriterion("SUB_STATE >", value, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_STATE >=", value, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateLessThan(String value) {
            addCriterion("SUB_STATE <", value, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateLessThanOrEqualTo(String value) {
            addCriterion("SUB_STATE <=", value, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateLike(String value) {
            addCriterion("SUB_STATE like", value, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateNotLike(String value) {
            addCriterion("SUB_STATE not like", value, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateIn(List<String> values) {
            addCriterion("SUB_STATE in", values, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateNotIn(List<String> values) {
            addCriterion("SUB_STATE not in", values, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateBetween(String value1, String value2) {
            addCriterion("SUB_STATE between", value1, value2, "subState");
            return (Criteria) this;
        }

        public Criteria andSubStateNotBetween(String value1, String value2) {
            addCriterion("SUB_STATE not between", value1, value2, "subState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateIsNull() {
            addCriterion("DOWNLOAD_STATE is null");
            return (Criteria) this;
        }

        public Criteria andDownloadStateIsNotNull() {
            addCriterion("DOWNLOAD_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadStateEqualTo(String value) {
            addCriterion("DOWNLOAD_STATE =", value, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateNotEqualTo(String value) {
            addCriterion("DOWNLOAD_STATE <>", value, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateGreaterThan(String value) {
            addCriterion("DOWNLOAD_STATE >", value, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateGreaterThanOrEqualTo(String value) {
            addCriterion("DOWNLOAD_STATE >=", value, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateLessThan(String value) {
            addCriterion("DOWNLOAD_STATE <", value, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateLessThanOrEqualTo(String value) {
            addCriterion("DOWNLOAD_STATE <=", value, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateLike(String value) {
            addCriterion("DOWNLOAD_STATE like", value, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateNotLike(String value) {
            addCriterion("DOWNLOAD_STATE not like", value, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateIn(List<String> values) {
            addCriterion("DOWNLOAD_STATE in", values, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateNotIn(List<String> values) {
            addCriterion("DOWNLOAD_STATE not in", values, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateBetween(String value1, String value2) {
            addCriterion("DOWNLOAD_STATE between", value1, value2, "downloadState");
            return (Criteria) this;
        }

        public Criteria andDownloadStateNotBetween(String value1, String value2) {
            addCriterion("DOWNLOAD_STATE not between", value1, value2, "downloadState");
            return (Criteria) this;
        }

        public Criteria andModeTotalIsNull() {
            addCriterion("MODE_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andModeTotalIsNotNull() {
            addCriterion("MODE_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andModeTotalEqualTo(String value) {
            addCriterion("MODE_TOTAL =", value, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalNotEqualTo(String value) {
            addCriterion("MODE_TOTAL <>", value, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalGreaterThan(String value) {
            addCriterion("MODE_TOTAL >", value, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_TOTAL >=", value, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalLessThan(String value) {
            addCriterion("MODE_TOTAL <", value, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalLessThanOrEqualTo(String value) {
            addCriterion("MODE_TOTAL <=", value, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalLike(String value) {
            addCriterion("MODE_TOTAL like", value, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalNotLike(String value) {
            addCriterion("MODE_TOTAL not like", value, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalIn(List<String> values) {
            addCriterion("MODE_TOTAL in", values, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalNotIn(List<String> values) {
            addCriterion("MODE_TOTAL not in", values, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalBetween(String value1, String value2) {
            addCriterion("MODE_TOTAL between", value1, value2, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeTotalNotBetween(String value1, String value2) {
            addCriterion("MODE_TOTAL not between", value1, value2, "modeTotal");
            return (Criteria) this;
        }

        public Criteria andModeProcessedIsNull() {
            addCriterion("MODE_PROCESSED is null");
            return (Criteria) this;
        }

        public Criteria andModeProcessedIsNotNull() {
            addCriterion("MODE_PROCESSED is not null");
            return (Criteria) this;
        }

        public Criteria andModeProcessedEqualTo(String value) {
            addCriterion("MODE_PROCESSED =", value, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedNotEqualTo(String value) {
            addCriterion("MODE_PROCESSED <>", value, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedGreaterThan(String value) {
            addCriterion("MODE_PROCESSED >", value, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_PROCESSED >=", value, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedLessThan(String value) {
            addCriterion("MODE_PROCESSED <", value, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedLessThanOrEqualTo(String value) {
            addCriterion("MODE_PROCESSED <=", value, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedLike(String value) {
            addCriterion("MODE_PROCESSED like", value, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedNotLike(String value) {
            addCriterion("MODE_PROCESSED not like", value, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedIn(List<String> values) {
            addCriterion("MODE_PROCESSED in", values, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedNotIn(List<String> values) {
            addCriterion("MODE_PROCESSED not in", values, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedBetween(String value1, String value2) {
            addCriterion("MODE_PROCESSED between", value1, value2, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeProcessedNotBetween(String value1, String value2) {
            addCriterion("MODE_PROCESSED not between", value1, value2, "modeProcessed");
            return (Criteria) this;
        }

        public Criteria andModeResultPathIsNull() {
            addCriterion("MODE_RESULT_PATH is null");
            return (Criteria) this;
        }

        public Criteria andModeResultPathIsNotNull() {
            addCriterion("MODE_RESULT_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andModeResultPathEqualTo(String value) {
            addCriterion("MODE_RESULT_PATH =", value, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathNotEqualTo(String value) {
            addCriterion("MODE_RESULT_PATH <>", value, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathGreaterThan(String value) {
            addCriterion("MODE_RESULT_PATH >", value, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_RESULT_PATH >=", value, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathLessThan(String value) {
            addCriterion("MODE_RESULT_PATH <", value, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathLessThanOrEqualTo(String value) {
            addCriterion("MODE_RESULT_PATH <=", value, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathLike(String value) {
            addCriterion("MODE_RESULT_PATH like", value, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathNotLike(String value) {
            addCriterion("MODE_RESULT_PATH not like", value, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathIn(List<String> values) {
            addCriterion("MODE_RESULT_PATH in", values, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathNotIn(List<String> values) {
            addCriterion("MODE_RESULT_PATH not in", values, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathBetween(String value1, String value2) {
            addCriterion("MODE_RESULT_PATH between", value1, value2, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andModeResultPathNotBetween(String value1, String value2) {
            addCriterion("MODE_RESULT_PATH not between", value1, value2, "modeResultPath");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeIsNull() {
            addCriterion("RESULT_FILE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeIsNotNull() {
            addCriterion("RESULT_FILE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeEqualTo(String value) {
            addCriterion("RESULT_FILE_TYPE =", value, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeNotEqualTo(String value) {
            addCriterion("RESULT_FILE_TYPE <>", value, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeGreaterThan(String value) {
            addCriterion("RESULT_FILE_TYPE >", value, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeGreaterThanOrEqualTo(String value) {
            addCriterion("RESULT_FILE_TYPE >=", value, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeLessThan(String value) {
            addCriterion("RESULT_FILE_TYPE <", value, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeLessThanOrEqualTo(String value) {
            addCriterion("RESULT_FILE_TYPE <=", value, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeLike(String value) {
            addCriterion("RESULT_FILE_TYPE like", value, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeNotLike(String value) {
            addCriterion("RESULT_FILE_TYPE not like", value, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeIn(List<String> values) {
            addCriterion("RESULT_FILE_TYPE in", values, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeNotIn(List<String> values) {
            addCriterion("RESULT_FILE_TYPE not in", values, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeBetween(String value1, String value2) {
            addCriterion("RESULT_FILE_TYPE between", value1, value2, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andResultFileTypeNotBetween(String value1, String value2) {
            addCriterion("RESULT_FILE_TYPE not between", value1, value2, "resultFileType");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterIsNull() {
            addCriterion("MODE_DELIMITER is null");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterIsNotNull() {
            addCriterion("MODE_DELIMITER is not null");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterEqualTo(String value) {
            addCriterion("MODE_DELIMITER =", value, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterNotEqualTo(String value) {
            addCriterion("MODE_DELIMITER <>", value, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterGreaterThan(String value) {
            addCriterion("MODE_DELIMITER >", value, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_DELIMITER >=", value, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterLessThan(String value) {
            addCriterion("MODE_DELIMITER <", value, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterLessThanOrEqualTo(String value) {
            addCriterion("MODE_DELIMITER <=", value, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterLike(String value) {
            addCriterion("MODE_DELIMITER like", value, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterNotLike(String value) {
            addCriterion("MODE_DELIMITER not like", value, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterIn(List<String> values) {
            addCriterion("MODE_DELIMITER in", values, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterNotIn(List<String> values) {
            addCriterion("MODE_DELIMITER not in", values, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterBetween(String value1, String value2) {
            addCriterion("MODE_DELIMITER between", value1, value2, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeDelimiterNotBetween(String value1, String value2) {
            addCriterion("MODE_DELIMITER not between", value1, value2, "modeDelimiter");
            return (Criteria) this;
        }

        public Criteria andModeResultNameIsNull() {
            addCriterion("MODE_RESULT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andModeResultNameIsNotNull() {
            addCriterion("MODE_RESULT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andModeResultNameEqualTo(String value) {
            addCriterion("MODE_RESULT_NAME =", value, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameNotEqualTo(String value) {
            addCriterion("MODE_RESULT_NAME <>", value, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameGreaterThan(String value) {
            addCriterion("MODE_RESULT_NAME >", value, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_RESULT_NAME >=", value, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameLessThan(String value) {
            addCriterion("MODE_RESULT_NAME <", value, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameLessThanOrEqualTo(String value) {
            addCriterion("MODE_RESULT_NAME <=", value, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameLike(String value) {
            addCriterion("MODE_RESULT_NAME like", value, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameNotLike(String value) {
            addCriterion("MODE_RESULT_NAME not like", value, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameIn(List<String> values) {
            addCriterion("MODE_RESULT_NAME in", values, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameNotIn(List<String> values) {
            addCriterion("MODE_RESULT_NAME not in", values, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameBetween(String value1, String value2) {
            addCriterion("MODE_RESULT_NAME between", value1, value2, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeResultNameNotBetween(String value1, String value2) {
            addCriterion("MODE_RESULT_NAME not between", value1, value2, "modeResultName");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathIsNull() {
            addCriterion("MODE_UPLOAD_PATH is null");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathIsNotNull() {
            addCriterion("MODE_UPLOAD_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathEqualTo(String value) {
            addCriterion("MODE_UPLOAD_PATH =", value, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathNotEqualTo(String value) {
            addCriterion("MODE_UPLOAD_PATH <>", value, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathGreaterThan(String value) {
            addCriterion("MODE_UPLOAD_PATH >", value, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_UPLOAD_PATH >=", value, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathLessThan(String value) {
            addCriterion("MODE_UPLOAD_PATH <", value, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathLessThanOrEqualTo(String value) {
            addCriterion("MODE_UPLOAD_PATH <=", value, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathLike(String value) {
            addCriterion("MODE_UPLOAD_PATH like", value, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathNotLike(String value) {
            addCriterion("MODE_UPLOAD_PATH not like", value, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathIn(List<String> values) {
            addCriterion("MODE_UPLOAD_PATH in", values, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathNotIn(List<String> values) {
            addCriterion("MODE_UPLOAD_PATH not in", values, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathBetween(String value1, String value2) {
            addCriterion("MODE_UPLOAD_PATH between", value1, value2, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadPathNotBetween(String value1, String value2) {
            addCriterion("MODE_UPLOAD_PATH not between", value1, value2, "modeUploadPath");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameIsNull() {
            addCriterion("MODE_UPLOAD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameIsNotNull() {
            addCriterion("MODE_UPLOAD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameEqualTo(String value) {
            addCriterion("MODE_UPLOAD_NAME =", value, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameNotEqualTo(String value) {
            addCriterion("MODE_UPLOAD_NAME <>", value, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameGreaterThan(String value) {
            addCriterion("MODE_UPLOAD_NAME >", value, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_UPLOAD_NAME >=", value, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameLessThan(String value) {
            addCriterion("MODE_UPLOAD_NAME <", value, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameLessThanOrEqualTo(String value) {
            addCriterion("MODE_UPLOAD_NAME <=", value, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameLike(String value) {
            addCriterion("MODE_UPLOAD_NAME like", value, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameNotLike(String value) {
            addCriterion("MODE_UPLOAD_NAME not like", value, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameIn(List<String> values) {
            addCriterion("MODE_UPLOAD_NAME in", values, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameNotIn(List<String> values) {
            addCriterion("MODE_UPLOAD_NAME not in", values, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameBetween(String value1, String value2) {
            addCriterion("MODE_UPLOAD_NAME between", value1, value2, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andModeUploadNameNotBetween(String value1, String value2) {
            addCriterion("MODE_UPLOAD_NAME not between", value1, value2, "modeUploadName");
            return (Criteria) this;
        }

        public Criteria andTxnIdIsNull() {
            addCriterion("TXN_ID is null");
            return (Criteria) this;
        }

        public Criteria andTxnIdIsNotNull() {
            addCriterion("TXN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTxnIdEqualTo(String value) {
            addCriterion("TXN_ID =", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotEqualTo(String value) {
            addCriterion("TXN_ID <>", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdGreaterThan(String value) {
            addCriterion("TXN_ID >", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_ID >=", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLessThan(String value) {
            addCriterion("TXN_ID <", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLessThanOrEqualTo(String value) {
            addCriterion("TXN_ID <=", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLike(String value) {
            addCriterion("TXN_ID like", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotLike(String value) {
            addCriterion("TXN_ID not like", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdIn(List<String> values) {
            addCriterion("TXN_ID in", values, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotIn(List<String> values) {
            addCriterion("TXN_ID not in", values, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdBetween(String value1, String value2) {
            addCriterion("TXN_ID between", value1, value2, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotBetween(String value1, String value2) {
            addCriterion("TXN_ID not between", value1, value2, "txnId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 21 17:49:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATA_MODE_TXN_INFO
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}