package cn.com.easypay.mapper;

public class DataxResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.id
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.start_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String startTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.end_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String endTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.total_costs
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String totalCosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.byte_speed_per_second
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String byteSpeedPerSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.record_speed_per_second
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String recordSpeedPerSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.total_read_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String totalReadRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.total_error_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String totalErrorRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.transformer_succeed_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String transformerSucceedRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.transformer_failed_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String transformerFailedRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.transformer_filter_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String transformerFilterRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.read_succeed_bytes
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String readSucceedBytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.end_transfer_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String endTransferTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.start_transfer_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String startTransferTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAX_RESULT.transfer_costs
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    private String transferCosts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.id
     *
     * @return the value of DATAX_RESULT.id
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.id
     *
     * @param id the value for DATAX_RESULT.id
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.start_time_stamp
     *
     * @return the value of DATAX_RESULT.start_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getStartTimeStamp() {
        return startTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.start_time_stamp
     *
     * @param startTimeStamp the value for DATAX_RESULT.start_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setStartTimeStamp(String startTimeStamp) {
        this.startTimeStamp = startTimeStamp == null ? null : startTimeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.end_time_stamp
     *
     * @return the value of DATAX_RESULT.end_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getEndTimeStamp() {
        return endTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.end_time_stamp
     *
     * @param endTimeStamp the value for DATAX_RESULT.end_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setEndTimeStamp(String endTimeStamp) {
        this.endTimeStamp = endTimeStamp == null ? null : endTimeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.total_costs
     *
     * @return the value of DATAX_RESULT.total_costs
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getTotalCosts() {
        return totalCosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.total_costs
     *
     * @param totalCosts the value for DATAX_RESULT.total_costs
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setTotalCosts(String totalCosts) {
        this.totalCosts = totalCosts == null ? null : totalCosts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.byte_speed_per_second
     *
     * @return the value of DATAX_RESULT.byte_speed_per_second
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getByteSpeedPerSecond() {
        return byteSpeedPerSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.byte_speed_per_second
     *
     * @param byteSpeedPerSecond the value for DATAX_RESULT.byte_speed_per_second
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setByteSpeedPerSecond(String byteSpeedPerSecond) {
        this.byteSpeedPerSecond = byteSpeedPerSecond == null ? null : byteSpeedPerSecond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.record_speed_per_second
     *
     * @return the value of DATAX_RESULT.record_speed_per_second
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getRecordSpeedPerSecond() {
        return recordSpeedPerSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.record_speed_per_second
     *
     * @param recordSpeedPerSecond the value for DATAX_RESULT.record_speed_per_second
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setRecordSpeedPerSecond(String recordSpeedPerSecond) {
        this.recordSpeedPerSecond = recordSpeedPerSecond == null ? null : recordSpeedPerSecond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.total_read_records
     *
     * @return the value of DATAX_RESULT.total_read_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getTotalReadRecords() {
        return totalReadRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.total_read_records
     *
     * @param totalReadRecords the value for DATAX_RESULT.total_read_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setTotalReadRecords(String totalReadRecords) {
        this.totalReadRecords = totalReadRecords == null ? null : totalReadRecords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.total_error_records
     *
     * @return the value of DATAX_RESULT.total_error_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getTotalErrorRecords() {
        return totalErrorRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.total_error_records
     *
     * @param totalErrorRecords the value for DATAX_RESULT.total_error_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setTotalErrorRecords(String totalErrorRecords) {
        this.totalErrorRecords = totalErrorRecords == null ? null : totalErrorRecords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.transformer_succeed_records
     *
     * @return the value of DATAX_RESULT.transformer_succeed_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getTransformerSucceedRecords() {
        return transformerSucceedRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.transformer_succeed_records
     *
     * @param transformerSucceedRecords the value for DATAX_RESULT.transformer_succeed_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setTransformerSucceedRecords(String transformerSucceedRecords) {
        this.transformerSucceedRecords = transformerSucceedRecords == null ? null : transformerSucceedRecords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.transformer_failed_records
     *
     * @return the value of DATAX_RESULT.transformer_failed_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getTransformerFailedRecords() {
        return transformerFailedRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.transformer_failed_records
     *
     * @param transformerFailedRecords the value for DATAX_RESULT.transformer_failed_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setTransformerFailedRecords(String transformerFailedRecords) {
        this.transformerFailedRecords = transformerFailedRecords == null ? null : transformerFailedRecords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.transformer_filter_records
     *
     * @return the value of DATAX_RESULT.transformer_filter_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getTransformerFilterRecords() {
        return transformerFilterRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.transformer_filter_records
     *
     * @param transformerFilterRecords the value for DATAX_RESULT.transformer_filter_records
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setTransformerFilterRecords(String transformerFilterRecords) {
        this.transformerFilterRecords = transformerFilterRecords == null ? null : transformerFilterRecords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.read_succeed_bytes
     *
     * @return the value of DATAX_RESULT.read_succeed_bytes
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getReadSucceedBytes() {
        return readSucceedBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.read_succeed_bytes
     *
     * @param readSucceedBytes the value for DATAX_RESULT.read_succeed_bytes
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setReadSucceedBytes(String readSucceedBytes) {
        this.readSucceedBytes = readSucceedBytes == null ? null : readSucceedBytes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.end_transfer_time_stamp
     *
     * @return the value of DATAX_RESULT.end_transfer_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getEndTransferTimeStamp() {
        return endTransferTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.end_transfer_time_stamp
     *
     * @param endTransferTimeStamp the value for DATAX_RESULT.end_transfer_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setEndTransferTimeStamp(String endTransferTimeStamp) {
        this.endTransferTimeStamp = endTransferTimeStamp == null ? null : endTransferTimeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.start_transfer_time_stamp
     *
     * @return the value of DATAX_RESULT.start_transfer_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getStartTransferTimeStamp() {
        return startTransferTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.start_transfer_time_stamp
     *
     * @param startTransferTimeStamp the value for DATAX_RESULT.start_transfer_time_stamp
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setStartTransferTimeStamp(String startTransferTimeStamp) {
        this.startTransferTimeStamp = startTransferTimeStamp == null ? null : startTransferTimeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAX_RESULT.transfer_costs
     *
     * @return the value of DATAX_RESULT.transfer_costs
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getTransferCosts() {
        return transferCosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAX_RESULT.transfer_costs
     *
     * @param transferCosts the value for DATAX_RESULT.transfer_costs
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setTransferCosts(String transferCosts) {
        this.transferCosts = transferCosts == null ? null : transferCosts.trim();
    }
}