package cn.com.easypay.mapper;

import java.util.ArrayList;
import java.util.List;

public class DataxResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public DataxResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampIsNull() {
            addCriterion("start_time_stamp is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampIsNotNull() {
            addCriterion("start_time_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampEqualTo(String value) {
            addCriterion("start_time_stamp =", value, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampNotEqualTo(String value) {
            addCriterion("start_time_stamp <>", value, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampGreaterThan(String value) {
            addCriterion("start_time_stamp >", value, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampGreaterThanOrEqualTo(String value) {
            addCriterion("start_time_stamp >=", value, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampLessThan(String value) {
            addCriterion("start_time_stamp <", value, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampLessThanOrEqualTo(String value) {
            addCriterion("start_time_stamp <=", value, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampLike(String value) {
            addCriterion("start_time_stamp like", value, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampNotLike(String value) {
            addCriterion("start_time_stamp not like", value, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampIn(List<String> values) {
            addCriterion("start_time_stamp in", values, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampNotIn(List<String> values) {
            addCriterion("start_time_stamp not in", values, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampBetween(String value1, String value2) {
            addCriterion("start_time_stamp between", value1, value2, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTimeStampNotBetween(String value1, String value2) {
            addCriterion("start_time_stamp not between", value1, value2, "startTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampIsNull() {
            addCriterion("end_time_stamp is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampIsNotNull() {
            addCriterion("end_time_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampEqualTo(String value) {
            addCriterion("end_time_stamp =", value, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampNotEqualTo(String value) {
            addCriterion("end_time_stamp <>", value, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampGreaterThan(String value) {
            addCriterion("end_time_stamp >", value, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampGreaterThanOrEqualTo(String value) {
            addCriterion("end_time_stamp >=", value, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampLessThan(String value) {
            addCriterion("end_time_stamp <", value, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampLessThanOrEqualTo(String value) {
            addCriterion("end_time_stamp <=", value, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampLike(String value) {
            addCriterion("end_time_stamp like", value, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampNotLike(String value) {
            addCriterion("end_time_stamp not like", value, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampIn(List<String> values) {
            addCriterion("end_time_stamp in", values, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampNotIn(List<String> values) {
            addCriterion("end_time_stamp not in", values, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampBetween(String value1, String value2) {
            addCriterion("end_time_stamp between", value1, value2, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTimeStampNotBetween(String value1, String value2) {
            addCriterion("end_time_stamp not between", value1, value2, "endTimeStamp");
            return (Criteria) this;
        }

        public Criteria andTotalCostsIsNull() {
            addCriterion("total_costs is null");
            return (Criteria) this;
        }

        public Criteria andTotalCostsIsNotNull() {
            addCriterion("total_costs is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCostsEqualTo(String value) {
            addCriterion("total_costs =", value, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsNotEqualTo(String value) {
            addCriterion("total_costs <>", value, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsGreaterThan(String value) {
            addCriterion("total_costs >", value, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsGreaterThanOrEqualTo(String value) {
            addCriterion("total_costs >=", value, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsLessThan(String value) {
            addCriterion("total_costs <", value, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsLessThanOrEqualTo(String value) {
            addCriterion("total_costs <=", value, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsLike(String value) {
            addCriterion("total_costs like", value, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsNotLike(String value) {
            addCriterion("total_costs not like", value, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsIn(List<String> values) {
            addCriterion("total_costs in", values, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsNotIn(List<String> values) {
            addCriterion("total_costs not in", values, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsBetween(String value1, String value2) {
            addCriterion("total_costs between", value1, value2, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andTotalCostsNotBetween(String value1, String value2) {
            addCriterion("total_costs not between", value1, value2, "totalCosts");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondIsNull() {
            addCriterion("byte_speed_per_second is null");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondIsNotNull() {
            addCriterion("byte_speed_per_second is not null");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondEqualTo(String value) {
            addCriterion("byte_speed_per_second =", value, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondNotEqualTo(String value) {
            addCriterion("byte_speed_per_second <>", value, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondGreaterThan(String value) {
            addCriterion("byte_speed_per_second >", value, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondGreaterThanOrEqualTo(String value) {
            addCriterion("byte_speed_per_second >=", value, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondLessThan(String value) {
            addCriterion("byte_speed_per_second <", value, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondLessThanOrEqualTo(String value) {
            addCriterion("byte_speed_per_second <=", value, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondLike(String value) {
            addCriterion("byte_speed_per_second like", value, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondNotLike(String value) {
            addCriterion("byte_speed_per_second not like", value, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondIn(List<String> values) {
            addCriterion("byte_speed_per_second in", values, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondNotIn(List<String> values) {
            addCriterion("byte_speed_per_second not in", values, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondBetween(String value1, String value2) {
            addCriterion("byte_speed_per_second between", value1, value2, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andByteSpeedPerSecondNotBetween(String value1, String value2) {
            addCriterion("byte_speed_per_second not between", value1, value2, "byteSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondIsNull() {
            addCriterion("record_speed_per_second is null");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondIsNotNull() {
            addCriterion("record_speed_per_second is not null");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondEqualTo(String value) {
            addCriterion("record_speed_per_second =", value, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondNotEqualTo(String value) {
            addCriterion("record_speed_per_second <>", value, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondGreaterThan(String value) {
            addCriterion("record_speed_per_second >", value, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondGreaterThanOrEqualTo(String value) {
            addCriterion("record_speed_per_second >=", value, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondLessThan(String value) {
            addCriterion("record_speed_per_second <", value, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondLessThanOrEqualTo(String value) {
            addCriterion("record_speed_per_second <=", value, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondLike(String value) {
            addCriterion("record_speed_per_second like", value, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondNotLike(String value) {
            addCriterion("record_speed_per_second not like", value, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondIn(List<String> values) {
            addCriterion("record_speed_per_second in", values, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondNotIn(List<String> values) {
            addCriterion("record_speed_per_second not in", values, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondBetween(String value1, String value2) {
            addCriterion("record_speed_per_second between", value1, value2, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andRecordSpeedPerSecondNotBetween(String value1, String value2) {
            addCriterion("record_speed_per_second not between", value1, value2, "recordSpeedPerSecond");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsIsNull() {
            addCriterion("total_read_records is null");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsIsNotNull() {
            addCriterion("total_read_records is not null");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsEqualTo(String value) {
            addCriterion("total_read_records =", value, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsNotEqualTo(String value) {
            addCriterion("total_read_records <>", value, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsGreaterThan(String value) {
            addCriterion("total_read_records >", value, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsGreaterThanOrEqualTo(String value) {
            addCriterion("total_read_records >=", value, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsLessThan(String value) {
            addCriterion("total_read_records <", value, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsLessThanOrEqualTo(String value) {
            addCriterion("total_read_records <=", value, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsLike(String value) {
            addCriterion("total_read_records like", value, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsNotLike(String value) {
            addCriterion("total_read_records not like", value, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsIn(List<String> values) {
            addCriterion("total_read_records in", values, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsNotIn(List<String> values) {
            addCriterion("total_read_records not in", values, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsBetween(String value1, String value2) {
            addCriterion("total_read_records between", value1, value2, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalReadRecordsNotBetween(String value1, String value2) {
            addCriterion("total_read_records not between", value1, value2, "totalReadRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsIsNull() {
            addCriterion("total_error_records is null");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsIsNotNull() {
            addCriterion("total_error_records is not null");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsEqualTo(String value) {
            addCriterion("total_error_records =", value, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsNotEqualTo(String value) {
            addCriterion("total_error_records <>", value, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsGreaterThan(String value) {
            addCriterion("total_error_records >", value, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsGreaterThanOrEqualTo(String value) {
            addCriterion("total_error_records >=", value, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsLessThan(String value) {
            addCriterion("total_error_records <", value, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsLessThanOrEqualTo(String value) {
            addCriterion("total_error_records <=", value, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsLike(String value) {
            addCriterion("total_error_records like", value, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsNotLike(String value) {
            addCriterion("total_error_records not like", value, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsIn(List<String> values) {
            addCriterion("total_error_records in", values, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsNotIn(List<String> values) {
            addCriterion("total_error_records not in", values, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsBetween(String value1, String value2) {
            addCriterion("total_error_records between", value1, value2, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTotalErrorRecordsNotBetween(String value1, String value2) {
            addCriterion("total_error_records not between", value1, value2, "totalErrorRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsIsNull() {
            addCriterion("transformer_succeed_records is null");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsIsNotNull() {
            addCriterion("transformer_succeed_records is not null");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsEqualTo(String value) {
            addCriterion("transformer_succeed_records =", value, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsNotEqualTo(String value) {
            addCriterion("transformer_succeed_records <>", value, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsGreaterThan(String value) {
            addCriterion("transformer_succeed_records >", value, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsGreaterThanOrEqualTo(String value) {
            addCriterion("transformer_succeed_records >=", value, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsLessThan(String value) {
            addCriterion("transformer_succeed_records <", value, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsLessThanOrEqualTo(String value) {
            addCriterion("transformer_succeed_records <=", value, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsLike(String value) {
            addCriterion("transformer_succeed_records like", value, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsNotLike(String value) {
            addCriterion("transformer_succeed_records not like", value, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsIn(List<String> values) {
            addCriterion("transformer_succeed_records in", values, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsNotIn(List<String> values) {
            addCriterion("transformer_succeed_records not in", values, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsBetween(String value1, String value2) {
            addCriterion("transformer_succeed_records between", value1, value2, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerSucceedRecordsNotBetween(String value1, String value2) {
            addCriterion("transformer_succeed_records not between", value1, value2, "transformerSucceedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsIsNull() {
            addCriterion("transformer_failed_records is null");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsIsNotNull() {
            addCriterion("transformer_failed_records is not null");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsEqualTo(String value) {
            addCriterion("transformer_failed_records =", value, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsNotEqualTo(String value) {
            addCriterion("transformer_failed_records <>", value, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsGreaterThan(String value) {
            addCriterion("transformer_failed_records >", value, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsGreaterThanOrEqualTo(String value) {
            addCriterion("transformer_failed_records >=", value, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsLessThan(String value) {
            addCriterion("transformer_failed_records <", value, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsLessThanOrEqualTo(String value) {
            addCriterion("transformer_failed_records <=", value, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsLike(String value) {
            addCriterion("transformer_failed_records like", value, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsNotLike(String value) {
            addCriterion("transformer_failed_records not like", value, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsIn(List<String> values) {
            addCriterion("transformer_failed_records in", values, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsNotIn(List<String> values) {
            addCriterion("transformer_failed_records not in", values, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsBetween(String value1, String value2) {
            addCriterion("transformer_failed_records between", value1, value2, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFailedRecordsNotBetween(String value1, String value2) {
            addCriterion("transformer_failed_records not between", value1, value2, "transformerFailedRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsIsNull() {
            addCriterion("transformer_filter_records is null");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsIsNotNull() {
            addCriterion("transformer_filter_records is not null");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsEqualTo(String value) {
            addCriterion("transformer_filter_records =", value, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsNotEqualTo(String value) {
            addCriterion("transformer_filter_records <>", value, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsGreaterThan(String value) {
            addCriterion("transformer_filter_records >", value, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsGreaterThanOrEqualTo(String value) {
            addCriterion("transformer_filter_records >=", value, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsLessThan(String value) {
            addCriterion("transformer_filter_records <", value, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsLessThanOrEqualTo(String value) {
            addCriterion("transformer_filter_records <=", value, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsLike(String value) {
            addCriterion("transformer_filter_records like", value, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsNotLike(String value) {
            addCriterion("transformer_filter_records not like", value, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsIn(List<String> values) {
            addCriterion("transformer_filter_records in", values, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsNotIn(List<String> values) {
            addCriterion("transformer_filter_records not in", values, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsBetween(String value1, String value2) {
            addCriterion("transformer_filter_records between", value1, value2, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andTransformerFilterRecordsNotBetween(String value1, String value2) {
            addCriterion("transformer_filter_records not between", value1, value2, "transformerFilterRecords");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesIsNull() {
            addCriterion("read_succeed_bytes is null");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesIsNotNull() {
            addCriterion("read_succeed_bytes is not null");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesEqualTo(String value) {
            addCriterion("read_succeed_bytes =", value, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesNotEqualTo(String value) {
            addCriterion("read_succeed_bytes <>", value, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesGreaterThan(String value) {
            addCriterion("read_succeed_bytes >", value, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesGreaterThanOrEqualTo(String value) {
            addCriterion("read_succeed_bytes >=", value, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesLessThan(String value) {
            addCriterion("read_succeed_bytes <", value, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesLessThanOrEqualTo(String value) {
            addCriterion("read_succeed_bytes <=", value, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesLike(String value) {
            addCriterion("read_succeed_bytes like", value, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesNotLike(String value) {
            addCriterion("read_succeed_bytes not like", value, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesIn(List<String> values) {
            addCriterion("read_succeed_bytes in", values, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesNotIn(List<String> values) {
            addCriterion("read_succeed_bytes not in", values, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesBetween(String value1, String value2) {
            addCriterion("read_succeed_bytes between", value1, value2, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andReadSucceedBytesNotBetween(String value1, String value2) {
            addCriterion("read_succeed_bytes not between", value1, value2, "readSucceedBytes");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampIsNull() {
            addCriterion("end_transfer_time_stamp is null");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampIsNotNull() {
            addCriterion("end_transfer_time_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampEqualTo(String value) {
            addCriterion("end_transfer_time_stamp =", value, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampNotEqualTo(String value) {
            addCriterion("end_transfer_time_stamp <>", value, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampGreaterThan(String value) {
            addCriterion("end_transfer_time_stamp >", value, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampGreaterThanOrEqualTo(String value) {
            addCriterion("end_transfer_time_stamp >=", value, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampLessThan(String value) {
            addCriterion("end_transfer_time_stamp <", value, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampLessThanOrEqualTo(String value) {
            addCriterion("end_transfer_time_stamp <=", value, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampLike(String value) {
            addCriterion("end_transfer_time_stamp like", value, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampNotLike(String value) {
            addCriterion("end_transfer_time_stamp not like", value, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampIn(List<String> values) {
            addCriterion("end_transfer_time_stamp in", values, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampNotIn(List<String> values) {
            addCriterion("end_transfer_time_stamp not in", values, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampBetween(String value1, String value2) {
            addCriterion("end_transfer_time_stamp between", value1, value2, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andEndTransferTimeStampNotBetween(String value1, String value2) {
            addCriterion("end_transfer_time_stamp not between", value1, value2, "endTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampIsNull() {
            addCriterion("start_transfer_time_stamp is null");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampIsNotNull() {
            addCriterion("start_transfer_time_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampEqualTo(String value) {
            addCriterion("start_transfer_time_stamp =", value, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampNotEqualTo(String value) {
            addCriterion("start_transfer_time_stamp <>", value, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampGreaterThan(String value) {
            addCriterion("start_transfer_time_stamp >", value, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampGreaterThanOrEqualTo(String value) {
            addCriterion("start_transfer_time_stamp >=", value, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampLessThan(String value) {
            addCriterion("start_transfer_time_stamp <", value, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampLessThanOrEqualTo(String value) {
            addCriterion("start_transfer_time_stamp <=", value, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampLike(String value) {
            addCriterion("start_transfer_time_stamp like", value, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampNotLike(String value) {
            addCriterion("start_transfer_time_stamp not like", value, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampIn(List<String> values) {
            addCriterion("start_transfer_time_stamp in", values, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampNotIn(List<String> values) {
            addCriterion("start_transfer_time_stamp not in", values, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampBetween(String value1, String value2) {
            addCriterion("start_transfer_time_stamp between", value1, value2, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andStartTransferTimeStampNotBetween(String value1, String value2) {
            addCriterion("start_transfer_time_stamp not between", value1, value2, "startTransferTimeStamp");
            return (Criteria) this;
        }

        public Criteria andTransferCostsIsNull() {
            addCriterion("transfer_costs is null");
            return (Criteria) this;
        }

        public Criteria andTransferCostsIsNotNull() {
            addCriterion("transfer_costs is not null");
            return (Criteria) this;
        }

        public Criteria andTransferCostsEqualTo(String value) {
            addCriterion("transfer_costs =", value, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsNotEqualTo(String value) {
            addCriterion("transfer_costs <>", value, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsGreaterThan(String value) {
            addCriterion("transfer_costs >", value, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_costs >=", value, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsLessThan(String value) {
            addCriterion("transfer_costs <", value, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsLessThanOrEqualTo(String value) {
            addCriterion("transfer_costs <=", value, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsLike(String value) {
            addCriterion("transfer_costs like", value, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsNotLike(String value) {
            addCriterion("transfer_costs not like", value, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsIn(List<String> values) {
            addCriterion("transfer_costs in", values, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsNotIn(List<String> values) {
            addCriterion("transfer_costs not in", values, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsBetween(String value1, String value2) {
            addCriterion("transfer_costs between", value1, value2, "transferCosts");
            return (Criteria) this;
        }

        public Criteria andTransferCostsNotBetween(String value1, String value2) {
            addCriterion("transfer_costs not between", value1, value2, "transferCosts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 21 13:38:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATAX_RESULT
     *
     * @mbggenerated Fri Aug 21 13:38:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}