package cn.com.easypay.mapper;

import java.math.BigDecimal;

public class DataModeTxnInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private BigDecimal modeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_WEIXIN
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.NOTICE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String noticeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.NOTICE_PHONE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String noticePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.NOTICE_EMAIL
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String noticeEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.NOTICE_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String noticeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.SUB_USERID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String subUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.SUB_CREATETIME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String subCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.SUB_UPDATETIME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String subUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.SUB_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String subState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.DOWNLOAD_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String downloadState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_TOTAL
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_PROCESSED
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeProcessed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_RESULT_PATH
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeResultPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.RESULT_FILE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String resultFileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_DELIMITER
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeDelimiter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_RESULT_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeResultName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_UPLOAD_PATH
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeUploadPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.MODE_UPLOAD_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String modeUploadName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.TXN_ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String txnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MODE_TXN_INFO.REMARK
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.ID
     *
     * @return the value of DATA_MODE_TXN_INFO.ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.ID
     *
     * @param id the value for DATA_MODE_TXN_INFO.ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_ID
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public BigDecimal getModeId() {
        return modeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_ID
     *
     * @param modeId the value for DATA_MODE_TXN_INFO.MODE_ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeId(BigDecimal modeId) {
        this.modeId = modeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_TYPE
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeType() {
        return modeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_TYPE
     *
     * @param modeType the value for DATA_MODE_TXN_INFO.MODE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeType(String modeType) {
        this.modeType = modeType == null ? null : modeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_NAME
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeName() {
        return modeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_NAME
     *
     * @param modeName the value for DATA_MODE_TXN_INFO.MODE_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeName(String modeName) {
        this.modeName = modeName == null ? null : modeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_WEIXIN
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_WEIXIN
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeWeixin() {
        return modeWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_WEIXIN
     *
     * @param modeWeixin the value for DATA_MODE_TXN_INFO.MODE_WEIXIN
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeWeixin(String modeWeixin) {
        this.modeWeixin = modeWeixin == null ? null : modeWeixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.NOTICE_TYPE
     *
     * @return the value of DATA_MODE_TXN_INFO.NOTICE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.NOTICE_TYPE
     *
     * @param noticeType the value for DATA_MODE_TXN_INFO.NOTICE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setNoticeType(String noticeType) {
        this.noticeType = noticeType == null ? null : noticeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.NOTICE_PHONE
     *
     * @return the value of DATA_MODE_TXN_INFO.NOTICE_PHONE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getNoticePhone() {
        return noticePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.NOTICE_PHONE
     *
     * @param noticePhone the value for DATA_MODE_TXN_INFO.NOTICE_PHONE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setNoticePhone(String noticePhone) {
        this.noticePhone = noticePhone == null ? null : noticePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.NOTICE_EMAIL
     *
     * @return the value of DATA_MODE_TXN_INFO.NOTICE_EMAIL
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getNoticeEmail() {
        return noticeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.NOTICE_EMAIL
     *
     * @param noticeEmail the value for DATA_MODE_TXN_INFO.NOTICE_EMAIL
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setNoticeEmail(String noticeEmail) {
        this.noticeEmail = noticeEmail == null ? null : noticeEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.NOTICE_STATE
     *
     * @return the value of DATA_MODE_TXN_INFO.NOTICE_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getNoticeState() {
        return noticeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.NOTICE_STATE
     *
     * @param noticeState the value for DATA_MODE_TXN_INFO.NOTICE_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setNoticeState(String noticeState) {
        this.noticeState = noticeState == null ? null : noticeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.SUB_USERID
     *
     * @return the value of DATA_MODE_TXN_INFO.SUB_USERID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getSubUserid() {
        return subUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.SUB_USERID
     *
     * @param subUserid the value for DATA_MODE_TXN_INFO.SUB_USERID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setSubUserid(String subUserid) {
        this.subUserid = subUserid == null ? null : subUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.SUB_CREATETIME
     *
     * @return the value of DATA_MODE_TXN_INFO.SUB_CREATETIME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getSubCreatetime() {
        return subCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.SUB_CREATETIME
     *
     * @param subCreatetime the value for DATA_MODE_TXN_INFO.SUB_CREATETIME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setSubCreatetime(String subCreatetime) {
        this.subCreatetime = subCreatetime == null ? null : subCreatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.SUB_UPDATETIME
     *
     * @return the value of DATA_MODE_TXN_INFO.SUB_UPDATETIME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getSubUpdatetime() {
        return subUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.SUB_UPDATETIME
     *
     * @param subUpdatetime the value for DATA_MODE_TXN_INFO.SUB_UPDATETIME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setSubUpdatetime(String subUpdatetime) {
        this.subUpdatetime = subUpdatetime == null ? null : subUpdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.SUB_STATE
     *
     * @return the value of DATA_MODE_TXN_INFO.SUB_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getSubState() {
        return subState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.SUB_STATE
     *
     * @param subState the value for DATA_MODE_TXN_INFO.SUB_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setSubState(String subState) {
        this.subState = subState == null ? null : subState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.DOWNLOAD_STATE
     *
     * @return the value of DATA_MODE_TXN_INFO.DOWNLOAD_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getDownloadState() {
        return downloadState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.DOWNLOAD_STATE
     *
     * @param downloadState the value for DATA_MODE_TXN_INFO.DOWNLOAD_STATE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setDownloadState(String downloadState) {
        this.downloadState = downloadState == null ? null : downloadState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_TOTAL
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_TOTAL
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeTotal() {
        return modeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_TOTAL
     *
     * @param modeTotal the value for DATA_MODE_TXN_INFO.MODE_TOTAL
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeTotal(String modeTotal) {
        this.modeTotal = modeTotal == null ? null : modeTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_PROCESSED
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_PROCESSED
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeProcessed() {
        return modeProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_PROCESSED
     *
     * @param modeProcessed the value for DATA_MODE_TXN_INFO.MODE_PROCESSED
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeProcessed(String modeProcessed) {
        this.modeProcessed = modeProcessed == null ? null : modeProcessed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_RESULT_PATH
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_RESULT_PATH
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeResultPath() {
        return modeResultPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_RESULT_PATH
     *
     * @param modeResultPath the value for DATA_MODE_TXN_INFO.MODE_RESULT_PATH
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeResultPath(String modeResultPath) {
        this.modeResultPath = modeResultPath == null ? null : modeResultPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.RESULT_FILE_TYPE
     *
     * @return the value of DATA_MODE_TXN_INFO.RESULT_FILE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getResultFileType() {
        return resultFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.RESULT_FILE_TYPE
     *
     * @param resultFileType the value for DATA_MODE_TXN_INFO.RESULT_FILE_TYPE
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setResultFileType(String resultFileType) {
        this.resultFileType = resultFileType == null ? null : resultFileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_DELIMITER
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_DELIMITER
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeDelimiter() {
        return modeDelimiter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_DELIMITER
     *
     * @param modeDelimiter the value for DATA_MODE_TXN_INFO.MODE_DELIMITER
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeDelimiter(String modeDelimiter) {
        this.modeDelimiter = modeDelimiter == null ? null : modeDelimiter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_RESULT_NAME
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_RESULT_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeResultName() {
        return modeResultName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_RESULT_NAME
     *
     * @param modeResultName the value for DATA_MODE_TXN_INFO.MODE_RESULT_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeResultName(String modeResultName) {
        this.modeResultName = modeResultName == null ? null : modeResultName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_UPLOAD_PATH
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_UPLOAD_PATH
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeUploadPath() {
        return modeUploadPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_UPLOAD_PATH
     *
     * @param modeUploadPath the value for DATA_MODE_TXN_INFO.MODE_UPLOAD_PATH
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeUploadPath(String modeUploadPath) {
        this.modeUploadPath = modeUploadPath == null ? null : modeUploadPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.MODE_UPLOAD_NAME
     *
     * @return the value of DATA_MODE_TXN_INFO.MODE_UPLOAD_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getModeUploadName() {
        return modeUploadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.MODE_UPLOAD_NAME
     *
     * @param modeUploadName the value for DATA_MODE_TXN_INFO.MODE_UPLOAD_NAME
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setModeUploadName(String modeUploadName) {
        this.modeUploadName = modeUploadName == null ? null : modeUploadName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.TXN_ID
     *
     * @return the value of DATA_MODE_TXN_INFO.TXN_ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.TXN_ID
     *
     * @param txnId the value for DATA_MODE_TXN_INFO.TXN_ID
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setTxnId(String txnId) {
        this.txnId = txnId == null ? null : txnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MODE_TXN_INFO.REMARK
     *
     * @return the value of DATA_MODE_TXN_INFO.REMARK
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MODE_TXN_INFO.REMARK
     *
     * @param remark the value for DATA_MODE_TXN_INFO.REMARK
     *
     * @mbggenerated Fri Aug 21 17:49:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}