package cn.com.easypay.mapper;

public class RuleMappingInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RULE_MAPPING_INFO.RULE
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RULE_MAPPING_INFO.VALUE
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RULE_MAPPING_INFO.TYPE
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RULE_MAPPING_INFO.REMARK
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    private String remark;

}