package cn.com.easypay.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuleMappingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RULE_MAPPING_INFO
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    int countByExample(RuleMappingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RULE_MAPPING_INFO
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    int deleteByExample(RuleMappingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RULE_MAPPING_INFO
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    int insert(RuleMappingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RULE_MAPPING_INFO
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    int insertSelective(RuleMappingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RULE_MAPPING_INFO
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    List<RuleMappingInfo> selectByExample(RuleMappingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RULE_MAPPING_INFO
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") RuleMappingInfo record, @Param("example") RuleMappingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RULE_MAPPING_INFO
     *
     * @mbggenerated Wed Aug 05 19:57:46 CST 2020
     */
    int updateByExample(@Param("record") RuleMappingInfo record, @Param("example") RuleMappingInfoExample example);
}