package cn.com.easypay.mapper;

import cn.com.easypay.mapper.TimingTask;
import cn.com.easypay.mapper.TimingTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimingTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int countByExample(TimingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int deleteByExample(TimingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int insert(TimingTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int insertSelective(TimingTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    List<TimingTask> selectByExample(TimingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    TimingTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") TimingTask record, @Param("example") TimingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int updateByExample(@Param("record") TimingTask record, @Param("example") TimingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int updateByPrimaryKeySelective(TimingTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    int updateByPrimaryKey(TimingTask record);
}