package cn.com.easypay.mapper;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TimingTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public TimingTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andModeIdIsNull() {
            addCriterion("MODE_ID is null");
            return (Criteria) this;
        }

        public Criteria andModeIdIsNotNull() {
            addCriterion("MODE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModeIdEqualTo(BigDecimal value) {
            addCriterion("MODE_ID =", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdNotEqualTo(BigDecimal value) {
            addCriterion("MODE_ID <>", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdGreaterThan(BigDecimal value) {
            addCriterion("MODE_ID >", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MODE_ID >=", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdLessThan(BigDecimal value) {
            addCriterion("MODE_ID <", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MODE_ID <=", value, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdIn(List<BigDecimal> values) {
            addCriterion("MODE_ID in", values, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdNotIn(List<BigDecimal> values) {
            addCriterion("MODE_ID not in", values, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MODE_ID between", value1, value2, "modeId");
            return (Criteria) this;
        }

        public Criteria andModeIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MODE_ID not between", value1, value2, "modeId");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNull() {
            addCriterion("OPERATE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNotNull() {
            addCriterion("OPERATE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeEqualTo(Integer value) {
            addCriterion("OPERATE_TYPE =", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotEqualTo(Integer value) {
            addCriterion("OPERATE_TYPE <>", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThan(Integer value) {
            addCriterion("OPERATE_TYPE >", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPERATE_TYPE >=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThan(Integer value) {
            addCriterion("OPERATE_TYPE <", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThanOrEqualTo(Integer value) {
            addCriterion("OPERATE_TYPE <=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIn(List<Integer> values) {
            addCriterion("OPERATE_TYPE in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotIn(List<Integer> values) {
            addCriterion("OPERATE_TYPE not in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeBetween(Integer value1, Integer value2) {
            addCriterion("OPERATE_TYPE between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("OPERATE_TYPE not between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupIsNull() {
            addCriterion("MODE_OPER_TYPE_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupIsNotNull() {
            addCriterion("MODE_OPER_TYPE_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupEqualTo(String value) {
            addCriterion("MODE_OPER_TYPE_GROUP =", value, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupNotEqualTo(String value) {
            addCriterion("MODE_OPER_TYPE_GROUP <>", value, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupGreaterThan(String value) {
            addCriterion("MODE_OPER_TYPE_GROUP >", value, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_OPER_TYPE_GROUP >=", value, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupLessThan(String value) {
            addCriterion("MODE_OPER_TYPE_GROUP <", value, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupLessThanOrEqualTo(String value) {
            addCriterion("MODE_OPER_TYPE_GROUP <=", value, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupLike(String value) {
            addCriterion("MODE_OPER_TYPE_GROUP like", value, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupNotLike(String value) {
            addCriterion("MODE_OPER_TYPE_GROUP not like", value, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupIn(List<String> values) {
            addCriterion("MODE_OPER_TYPE_GROUP in", values, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupNotIn(List<String> values) {
            addCriterion("MODE_OPER_TYPE_GROUP not in", values, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupBetween(String value1, String value2) {
            addCriterion("MODE_OPER_TYPE_GROUP between", value1, value2, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeGroupNotBetween(String value1, String value2) {
            addCriterion("MODE_OPER_TYPE_GROUP not between", value1, value2, "modeOperTypeGroup");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderIsNull() {
            addCriterion("MODE_OPER_TYPE_OPDER is null");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderIsNotNull() {
            addCriterion("MODE_OPER_TYPE_OPDER is not null");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderEqualTo(String value) {
            addCriterion("MODE_OPER_TYPE_OPDER =", value, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderNotEqualTo(String value) {
            addCriterion("MODE_OPER_TYPE_OPDER <>", value, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderGreaterThan(String value) {
            addCriterion("MODE_OPER_TYPE_OPDER >", value, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_OPER_TYPE_OPDER >=", value, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderLessThan(String value) {
            addCriterion("MODE_OPER_TYPE_OPDER <", value, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderLessThanOrEqualTo(String value) {
            addCriterion("MODE_OPER_TYPE_OPDER <=", value, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderLike(String value) {
            addCriterion("MODE_OPER_TYPE_OPDER like", value, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderNotLike(String value) {
            addCriterion("MODE_OPER_TYPE_OPDER not like", value, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderIn(List<String> values) {
            addCriterion("MODE_OPER_TYPE_OPDER in", values, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderNotIn(List<String> values) {
            addCriterion("MODE_OPER_TYPE_OPDER not in", values, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderBetween(String value1, String value2) {
            addCriterion("MODE_OPER_TYPE_OPDER between", value1, value2, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeOperTypeOpderNotBetween(String value1, String value2) {
            addCriterion("MODE_OPER_TYPE_OPDER not between", value1, value2, "modeOperTypeOpder");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceIsNull() {
            addCriterion("MODE_DATASOURCE is null");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceIsNotNull() {
            addCriterion("MODE_DATASOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceEqualTo(String value) {
            addCriterion("MODE_DATASOURCE =", value, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceNotEqualTo(String value) {
            addCriterion("MODE_DATASOURCE <>", value, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceGreaterThan(String value) {
            addCriterion("MODE_DATASOURCE >", value, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceGreaterThanOrEqualTo(String value) {
            addCriterion("MODE_DATASOURCE >=", value, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceLessThan(String value) {
            addCriterion("MODE_DATASOURCE <", value, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceLessThanOrEqualTo(String value) {
            addCriterion("MODE_DATASOURCE <=", value, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceLike(String value) {
            addCriterion("MODE_DATASOURCE like", value, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceNotLike(String value) {
            addCriterion("MODE_DATASOURCE not like", value, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceIn(List<String> values) {
            addCriterion("MODE_DATASOURCE in", values, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceNotIn(List<String> values) {
            addCriterion("MODE_DATASOURCE not in", values, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceBetween(String value1, String value2) {
            addCriterion("MODE_DATASOURCE between", value1, value2, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andModeDatasourceNotBetween(String value1, String value2) {
            addCriterion("MODE_DATASOURCE not between", value1, value2, "modeDatasource");
            return (Criteria) this;
        }

        public Criteria andDataNameIsNull() {
            addCriterion("DATA_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDataNameIsNotNull() {
            addCriterion("DATA_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDataNameEqualTo(String value) {
            addCriterion("DATA_NAME =", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotEqualTo(String value) {
            addCriterion("DATA_NAME <>", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameGreaterThan(String value) {
            addCriterion("DATA_NAME >", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_NAME >=", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLessThan(String value) {
            addCriterion("DATA_NAME <", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLessThanOrEqualTo(String value) {
            addCriterion("DATA_NAME <=", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLike(String value) {
            addCriterion("DATA_NAME like", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotLike(String value) {
            addCriterion("DATA_NAME not like", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameIn(List<String> values) {
            addCriterion("DATA_NAME in", values, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotIn(List<String> values) {
            addCriterion("DATA_NAME not in", values, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameBetween(String value1, String value2) {
            addCriterion("DATA_NAME between", value1, value2, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotBetween(String value1, String value2) {
            addCriterion("DATA_NAME not between", value1, value2, "dataName");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("START_TIME =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("START_TIME <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("START_TIME >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("START_TIME >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("START_TIME <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("START_TIME <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("START_TIME like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("START_TIME not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("START_TIME in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("START_TIME not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("START_TIME between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("START_TIME not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("END_TIME like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("END_TIME not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeIsNull() {
            addCriterion("NEXT_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeIsNotNull() {
            addCriterion("NEXT_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeEqualTo(String value) {
            addCriterion("NEXT_START_TIME =", value, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeNotEqualTo(String value) {
            addCriterion("NEXT_START_TIME <>", value, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeGreaterThan(String value) {
            addCriterion("NEXT_START_TIME >", value, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("NEXT_START_TIME >=", value, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeLessThan(String value) {
            addCriterion("NEXT_START_TIME <", value, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeLessThanOrEqualTo(String value) {
            addCriterion("NEXT_START_TIME <=", value, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeLike(String value) {
            addCriterion("NEXT_START_TIME like", value, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeNotLike(String value) {
            addCriterion("NEXT_START_TIME not like", value, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeIn(List<String> values) {
            addCriterion("NEXT_START_TIME in", values, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeNotIn(List<String> values) {
            addCriterion("NEXT_START_TIME not in", values, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeBetween(String value1, String value2) {
            addCriterion("NEXT_START_TIME between", value1, value2, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andNextStartTimeNotBetween(String value1, String value2) {
            addCriterion("NEXT_START_TIME not between", value1, value2, "nextStartTime");
            return (Criteria) this;
        }

        public Criteria andIntervalDateIsNull() {
            addCriterion("INTERVAL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andIntervalDateIsNotNull() {
            addCriterion("INTERVAL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andIntervalDateEqualTo(String value) {
            addCriterion("INTERVAL_DATE =", value, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateNotEqualTo(String value) {
            addCriterion("INTERVAL_DATE <>", value, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateGreaterThan(String value) {
            addCriterion("INTERVAL_DATE >", value, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateGreaterThanOrEqualTo(String value) {
            addCriterion("INTERVAL_DATE >=", value, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateLessThan(String value) {
            addCriterion("INTERVAL_DATE <", value, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateLessThanOrEqualTo(String value) {
            addCriterion("INTERVAL_DATE <=", value, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateLike(String value) {
            addCriterion("INTERVAL_DATE like", value, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateNotLike(String value) {
            addCriterion("INTERVAL_DATE not like", value, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateIn(List<String> values) {
            addCriterion("INTERVAL_DATE in", values, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateNotIn(List<String> values) {
            addCriterion("INTERVAL_DATE not in", values, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateBetween(String value1, String value2) {
            addCriterion("INTERVAL_DATE between", value1, value2, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andIntervalDateNotBetween(String value1, String value2) {
            addCriterion("INTERVAL_DATE not between", value1, value2, "intervalDate");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupIsNull() {
            addCriterion("EXCUTE_SQL_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupIsNotNull() {
            addCriterion("EXCUTE_SQL_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupEqualTo(String value) {
            addCriterion("EXCUTE_SQL_GROUP =", value, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupNotEqualTo(String value) {
            addCriterion("EXCUTE_SQL_GROUP <>", value, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupGreaterThan(String value) {
            addCriterion("EXCUTE_SQL_GROUP >", value, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupGreaterThanOrEqualTo(String value) {
            addCriterion("EXCUTE_SQL_GROUP >=", value, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupLessThan(String value) {
            addCriterion("EXCUTE_SQL_GROUP <", value, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupLessThanOrEqualTo(String value) {
            addCriterion("EXCUTE_SQL_GROUP <=", value, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupLike(String value) {
            addCriterion("EXCUTE_SQL_GROUP like", value, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupNotLike(String value) {
            addCriterion("EXCUTE_SQL_GROUP not like", value, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupIn(List<String> values) {
            addCriterion("EXCUTE_SQL_GROUP in", values, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupNotIn(List<String> values) {
            addCriterion("EXCUTE_SQL_GROUP not in", values, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupBetween(String value1, String value2) {
            addCriterion("EXCUTE_SQL_GROUP between", value1, value2, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlGroupNotBetween(String value1, String value2) {
            addCriterion("EXCUTE_SQL_GROUP not between", value1, value2, "excuteSqlGroup");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderIsNull() {
            addCriterion("EXCUTE_SQL_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderIsNotNull() {
            addCriterion("EXCUTE_SQL_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderEqualTo(String value) {
            addCriterion("EXCUTE_SQL_ORDER =", value, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderNotEqualTo(String value) {
            addCriterion("EXCUTE_SQL_ORDER <>", value, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderGreaterThan(String value) {
            addCriterion("EXCUTE_SQL_ORDER >", value, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderGreaterThanOrEqualTo(String value) {
            addCriterion("EXCUTE_SQL_ORDER >=", value, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderLessThan(String value) {
            addCriterion("EXCUTE_SQL_ORDER <", value, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderLessThanOrEqualTo(String value) {
            addCriterion("EXCUTE_SQL_ORDER <=", value, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderLike(String value) {
            addCriterion("EXCUTE_SQL_ORDER like", value, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderNotLike(String value) {
            addCriterion("EXCUTE_SQL_ORDER not like", value, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderIn(List<String> values) {
            addCriterion("EXCUTE_SQL_ORDER in", values, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderNotIn(List<String> values) {
            addCriterion("EXCUTE_SQL_ORDER not in", values, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderBetween(String value1, String value2) {
            addCriterion("EXCUTE_SQL_ORDER between", value1, value2, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andExcuteSqlOrderNotBetween(String value1, String value2) {
            addCriterion("EXCUTE_SQL_ORDER not between", value1, value2, "excuteSqlOrder");
            return (Criteria) this;
        }

        public Criteria andStatueIsNull() {
            addCriterion("STATUE is null");
            return (Criteria) this;
        }

        public Criteria andStatueIsNotNull() {
            addCriterion("STATUE is not null");
            return (Criteria) this;
        }

        public Criteria andStatueEqualTo(String value) {
            addCriterion("STATUE =", value, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueNotEqualTo(String value) {
            addCriterion("STATUE <>", value, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueGreaterThan(String value) {
            addCriterion("STATUE >", value, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueGreaterThanOrEqualTo(String value) {
            addCriterion("STATUE >=", value, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueLessThan(String value) {
            addCriterion("STATUE <", value, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueLessThanOrEqualTo(String value) {
            addCriterion("STATUE <=", value, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueLike(String value) {
            addCriterion("STATUE like", value, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueNotLike(String value) {
            addCriterion("STATUE not like", value, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueIn(List<String> values) {
            addCriterion("STATUE in", values, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueNotIn(List<String> values) {
            addCriterion("STATUE not in", values, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueBetween(String value1, String value2) {
            addCriterion("STATUE between", value1, value2, "statue");
            return (Criteria) this;
        }

        public Criteria andStatueNotBetween(String value1, String value2) {
            addCriterion("STATUE not between", value1, value2, "statue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TIMING_TASK
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 31 13:51:30 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TIMING_TASK
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}