package cn.com.easypay.mapper;

import java.math.BigDecimal;

public class TimingTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.USER_ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.MODE_ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private BigDecimal modeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.OPERATE_TYPE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private Integer operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.MODE_OPER_TYPE_GROUP
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String modeOperTypeGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.MODE_OPER_TYPE_OPDER
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String modeOperTypeOpder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.MODE_DATASOURCE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String modeDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.DATA_NAME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String dataName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.START_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.END_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.NEXT_START_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String nextStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.INTERVAL_DATE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String intervalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.EXCUTE_SQL_GROUP
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String excuteSqlGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.EXCUTE_SQL_ORDER
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String excuteSqlOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIMING_TASK.STATUE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    private String statue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.ID
     *
     * @return the value of TIMING_TASK.ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.ID
     *
     * @param id the value for TIMING_TASK.ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.USER_ID
     *
     * @return the value of TIMING_TASK.USER_ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.USER_ID
     *
     * @param userId the value for TIMING_TASK.USER_ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.MODE_ID
     *
     * @return the value of TIMING_TASK.MODE_ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public BigDecimal getModeId() {
        return modeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.MODE_ID
     *
     * @param modeId the value for TIMING_TASK.MODE_ID
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setModeId(BigDecimal modeId) {
        this.modeId = modeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.OPERATE_TYPE
     *
     * @return the value of TIMING_TASK.OPERATE_TYPE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.OPERATE_TYPE
     *
     * @param operateType the value for TIMING_TASK.OPERATE_TYPE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.MODE_OPER_TYPE_GROUP
     *
     * @return the value of TIMING_TASK.MODE_OPER_TYPE_GROUP
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getModeOperTypeGroup() {
        return modeOperTypeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.MODE_OPER_TYPE_GROUP
     *
     * @param modeOperTypeGroup the value for TIMING_TASK.MODE_OPER_TYPE_GROUP
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setModeOperTypeGroup(String modeOperTypeGroup) {
        this.modeOperTypeGroup = modeOperTypeGroup == null ? null : modeOperTypeGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.MODE_OPER_TYPE_OPDER
     *
     * @return the value of TIMING_TASK.MODE_OPER_TYPE_OPDER
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getModeOperTypeOpder() {
        return modeOperTypeOpder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.MODE_OPER_TYPE_OPDER
     *
     * @param modeOperTypeOpder the value for TIMING_TASK.MODE_OPER_TYPE_OPDER
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setModeOperTypeOpder(String modeOperTypeOpder) {
        this.modeOperTypeOpder = modeOperTypeOpder == null ? null : modeOperTypeOpder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.MODE_DATASOURCE
     *
     * @return the value of TIMING_TASK.MODE_DATASOURCE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getModeDatasource() {
        return modeDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.MODE_DATASOURCE
     *
     * @param modeDatasource the value for TIMING_TASK.MODE_DATASOURCE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setModeDatasource(String modeDatasource) {
        this.modeDatasource = modeDatasource == null ? null : modeDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.DATA_NAME
     *
     * @return the value of TIMING_TASK.DATA_NAME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getDataName() {
        return dataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.DATA_NAME
     *
     * @param dataName the value for TIMING_TASK.DATA_NAME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setDataName(String dataName) {
        this.dataName = dataName == null ? null : dataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.START_TIME
     *
     * @return the value of TIMING_TASK.START_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.START_TIME
     *
     * @param startTime the value for TIMING_TASK.START_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.END_TIME
     *
     * @return the value of TIMING_TASK.END_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.END_TIME
     *
     * @param endTime the value for TIMING_TASK.END_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.NEXT_START_TIME
     *
     * @return the value of TIMING_TASK.NEXT_START_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getNextStartTime() {
        return nextStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.NEXT_START_TIME
     *
     * @param nextStartTime the value for TIMING_TASK.NEXT_START_TIME
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setNextStartTime(String nextStartTime) {
        this.nextStartTime = nextStartTime == null ? null : nextStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.INTERVAL_DATE
     *
     * @return the value of TIMING_TASK.INTERVAL_DATE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getIntervalDate() {
        return intervalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.INTERVAL_DATE
     *
     * @param intervalDate the value for TIMING_TASK.INTERVAL_DATE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setIntervalDate(String intervalDate) {
        this.intervalDate = intervalDate == null ? null : intervalDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.EXCUTE_SQL_GROUP
     *
     * @return the value of TIMING_TASK.EXCUTE_SQL_GROUP
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getExcuteSqlGroup() {
        return excuteSqlGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.EXCUTE_SQL_GROUP
     *
     * @param excuteSqlGroup the value for TIMING_TASK.EXCUTE_SQL_GROUP
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setExcuteSqlGroup(String excuteSqlGroup) {
        this.excuteSqlGroup = excuteSqlGroup == null ? null : excuteSqlGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.EXCUTE_SQL_ORDER
     *
     * @return the value of TIMING_TASK.EXCUTE_SQL_ORDER
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getExcuteSqlOrder() {
        return excuteSqlOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.EXCUTE_SQL_ORDER
     *
     * @param excuteSqlOrder the value for TIMING_TASK.EXCUTE_SQL_ORDER
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setExcuteSqlOrder(String excuteSqlOrder) {
        this.excuteSqlOrder = excuteSqlOrder == null ? null : excuteSqlOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIMING_TASK.STATUE
     *
     * @return the value of TIMING_TASK.STATUE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public String getStatue() {
        return statue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIMING_TASK.STATUE
     *
     * @param statue the value for TIMING_TASK.STATUE
     *
     * @mbggenerated Mon Aug 31 13:51:30 CST 2020
     */
    public void setStatue(String statue) {
        this.statue = statue == null ? null : statue.trim();
    }
}