package com.test.bean;

import java.math.BigDecimal;

public class CSUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.USERID
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.USERNAME
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.CREATE_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.GROUPID
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.LIMIT_CODE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String limitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.LASTIP
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String lastip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.LASTDT
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String lastdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.STATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.INIT_PWD
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String initPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.LOGINTOTAL
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private BigDecimal logintotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.PASSWD_EXP
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String passwdExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.MOBILE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.EMAIL
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.DEPARTMENT
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.SP_BUTTON
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String spButton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.TYPE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.PASSWD_TYPE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String passwdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.EXP_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_user.PASSWD
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.USERID
     *
     * @return the value of cs_user.USERID
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.USERID
     *
     * @param userid the value for cs_user.USERID
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.USERNAME
     *
     * @return the value of cs_user.USERNAME
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.USERNAME
     *
     * @param username the value for cs_user.USERNAME
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.CREATE_DATE
     *
     * @return the value of cs_user.CREATE_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.CREATE_DATE
     *
     * @param createDate the value for cs_user.CREATE_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.GROUPID
     *
     * @return the value of cs_user.GROUPID
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.GROUPID
     *
     * @param groupid the value for cs_user.GROUPID
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.LIMIT_CODE
     *
     * @return the value of cs_user.LIMIT_CODE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getLimitCode() {
        return limitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.LIMIT_CODE
     *
     * @param limitCode the value for cs_user.LIMIT_CODE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setLimitCode(String limitCode) {
        this.limitCode = limitCode == null ? null : limitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.LASTIP
     *
     * @return the value of cs_user.LASTIP
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getLastip() {
        return lastip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.LASTIP
     *
     * @param lastip the value for cs_user.LASTIP
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setLastip(String lastip) {
        this.lastip = lastip == null ? null : lastip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.LASTDT
     *
     * @return the value of cs_user.LASTDT
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getLastdt() {
        return lastdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.LASTDT
     *
     * @param lastdt the value for cs_user.LASTDT
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setLastdt(String lastdt) {
        this.lastdt = lastdt == null ? null : lastdt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.STATE
     *
     * @return the value of cs_user.STATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.STATE
     *
     * @param state the value for cs_user.STATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.INIT_PWD
     *
     * @return the value of cs_user.INIT_PWD
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getInitPwd() {
        return initPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.INIT_PWD
     *
     * @param initPwd the value for cs_user.INIT_PWD
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setInitPwd(String initPwd) {
        this.initPwd = initPwd == null ? null : initPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.LOGINTOTAL
     *
     * @return the value of cs_user.LOGINTOTAL
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public BigDecimal getLogintotal() {
        return logintotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.LOGINTOTAL
     *
     * @param logintotal the value for cs_user.LOGINTOTAL
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setLogintotal(BigDecimal logintotal) {
        this.logintotal = logintotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.PASSWD_EXP
     *
     * @return the value of cs_user.PASSWD_EXP
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getPasswdExp() {
        return passwdExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.PASSWD_EXP
     *
     * @param passwdExp the value for cs_user.PASSWD_EXP
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setPasswdExp(String passwdExp) {
        this.passwdExp = passwdExp == null ? null : passwdExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.MOBILE
     *
     * @return the value of cs_user.MOBILE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.MOBILE
     *
     * @param mobile the value for cs_user.MOBILE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.EMAIL
     *
     * @return the value of cs_user.EMAIL
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.EMAIL
     *
     * @param email the value for cs_user.EMAIL
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.DEPARTMENT
     *
     * @return the value of cs_user.DEPARTMENT
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.DEPARTMENT
     *
     * @param department the value for cs_user.DEPARTMENT
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.SP_BUTTON
     *
     * @return the value of cs_user.SP_BUTTON
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getSpButton() {
        return spButton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.SP_BUTTON
     *
     * @param spButton the value for cs_user.SP_BUTTON
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setSpButton(String spButton) {
        this.spButton = spButton == null ? null : spButton.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.TYPE
     *
     * @return the value of cs_user.TYPE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.TYPE
     *
     * @param type the value for cs_user.TYPE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.PASSWD_TYPE
     *
     * @return the value of cs_user.PASSWD_TYPE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getPasswdType() {
        return passwdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.PASSWD_TYPE
     *
     * @param passwdType the value for cs_user.PASSWD_TYPE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setPasswdType(String passwdType) {
        this.passwdType = passwdType == null ? null : passwdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.UPDATE_DATE
     *
     * @return the value of cs_user.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.UPDATE_DATE
     *
     * @param updateDate the value for cs_user.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.EXP_DATE
     *
     * @return the value of cs_user.EXP_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.EXP_DATE
     *
     * @param expDate the value for cs_user.EXP_DATE
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setExpDate(String expDate) {
        this.expDate = expDate == null ? null : expDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_user.PASSWD
     *
     * @return the value of cs_user.PASSWD
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_user.PASSWD
     *
     * @param passwd the value for cs_user.PASSWD
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }
}