package com.test.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CSUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public CSUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNull() {
            addCriterion("GROUPID is null");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNotNull() {
            addCriterion("GROUPID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupidEqualTo(String value) {
            addCriterion("GROUPID =", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotEqualTo(String value) {
            addCriterion("GROUPID <>", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThan(String value) {
            addCriterion("GROUPID >", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThanOrEqualTo(String value) {
            addCriterion("GROUPID >=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThan(String value) {
            addCriterion("GROUPID <", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThanOrEqualTo(String value) {
            addCriterion("GROUPID <=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLike(String value) {
            addCriterion("GROUPID like", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotLike(String value) {
            addCriterion("GROUPID not like", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidIn(List<String> values) {
            addCriterion("GROUPID in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotIn(List<String> values) {
            addCriterion("GROUPID not in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidBetween(String value1, String value2) {
            addCriterion("GROUPID between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotBetween(String value1, String value2) {
            addCriterion("GROUPID not between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andLimitCodeIsNull() {
            addCriterion("LIMIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andLimitCodeIsNotNull() {
            addCriterion("LIMIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andLimitCodeEqualTo(String value) {
            addCriterion("LIMIT_CODE =", value, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeNotEqualTo(String value) {
            addCriterion("LIMIT_CODE <>", value, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeGreaterThan(String value) {
            addCriterion("LIMIT_CODE >", value, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("LIMIT_CODE >=", value, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeLessThan(String value) {
            addCriterion("LIMIT_CODE <", value, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeLessThanOrEqualTo(String value) {
            addCriterion("LIMIT_CODE <=", value, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeLike(String value) {
            addCriterion("LIMIT_CODE like", value, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeNotLike(String value) {
            addCriterion("LIMIT_CODE not like", value, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeIn(List<String> values) {
            addCriterion("LIMIT_CODE in", values, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeNotIn(List<String> values) {
            addCriterion("LIMIT_CODE not in", values, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeBetween(String value1, String value2) {
            addCriterion("LIMIT_CODE between", value1, value2, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLimitCodeNotBetween(String value1, String value2) {
            addCriterion("LIMIT_CODE not between", value1, value2, "limitCode");
            return (Criteria) this;
        }

        public Criteria andLastipIsNull() {
            addCriterion("LASTIP is null");
            return (Criteria) this;
        }

        public Criteria andLastipIsNotNull() {
            addCriterion("LASTIP is not null");
            return (Criteria) this;
        }

        public Criteria andLastipEqualTo(String value) {
            addCriterion("LASTIP =", value, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipNotEqualTo(String value) {
            addCriterion("LASTIP <>", value, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipGreaterThan(String value) {
            addCriterion("LASTIP >", value, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipGreaterThanOrEqualTo(String value) {
            addCriterion("LASTIP >=", value, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipLessThan(String value) {
            addCriterion("LASTIP <", value, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipLessThanOrEqualTo(String value) {
            addCriterion("LASTIP <=", value, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipLike(String value) {
            addCriterion("LASTIP like", value, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipNotLike(String value) {
            addCriterion("LASTIP not like", value, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipIn(List<String> values) {
            addCriterion("LASTIP in", values, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipNotIn(List<String> values) {
            addCriterion("LASTIP not in", values, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipBetween(String value1, String value2) {
            addCriterion("LASTIP between", value1, value2, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastipNotBetween(String value1, String value2) {
            addCriterion("LASTIP not between", value1, value2, "lastip");
            return (Criteria) this;
        }

        public Criteria andLastdtIsNull() {
            addCriterion("LASTDT is null");
            return (Criteria) this;
        }

        public Criteria andLastdtIsNotNull() {
            addCriterion("LASTDT is not null");
            return (Criteria) this;
        }

        public Criteria andLastdtEqualTo(String value) {
            addCriterion("LASTDT =", value, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtNotEqualTo(String value) {
            addCriterion("LASTDT <>", value, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtGreaterThan(String value) {
            addCriterion("LASTDT >", value, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtGreaterThanOrEqualTo(String value) {
            addCriterion("LASTDT >=", value, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtLessThan(String value) {
            addCriterion("LASTDT <", value, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtLessThanOrEqualTo(String value) {
            addCriterion("LASTDT <=", value, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtLike(String value) {
            addCriterion("LASTDT like", value, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtNotLike(String value) {
            addCriterion("LASTDT not like", value, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtIn(List<String> values) {
            addCriterion("LASTDT in", values, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtNotIn(List<String> values) {
            addCriterion("LASTDT not in", values, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtBetween(String value1, String value2) {
            addCriterion("LASTDT between", value1, value2, "lastdt");
            return (Criteria) this;
        }

        public Criteria andLastdtNotBetween(String value1, String value2) {
            addCriterion("LASTDT not between", value1, value2, "lastdt");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andInitPwdIsNull() {
            addCriterion("INIT_PWD is null");
            return (Criteria) this;
        }

        public Criteria andInitPwdIsNotNull() {
            addCriterion("INIT_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andInitPwdEqualTo(String value) {
            addCriterion("INIT_PWD =", value, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdNotEqualTo(String value) {
            addCriterion("INIT_PWD <>", value, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdGreaterThan(String value) {
            addCriterion("INIT_PWD >", value, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdGreaterThanOrEqualTo(String value) {
            addCriterion("INIT_PWD >=", value, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdLessThan(String value) {
            addCriterion("INIT_PWD <", value, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdLessThanOrEqualTo(String value) {
            addCriterion("INIT_PWD <=", value, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdLike(String value) {
            addCriterion("INIT_PWD like", value, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdNotLike(String value) {
            addCriterion("INIT_PWD not like", value, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdIn(List<String> values) {
            addCriterion("INIT_PWD in", values, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdNotIn(List<String> values) {
            addCriterion("INIT_PWD not in", values, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdBetween(String value1, String value2) {
            addCriterion("INIT_PWD between", value1, value2, "initPwd");
            return (Criteria) this;
        }

        public Criteria andInitPwdNotBetween(String value1, String value2) {
            addCriterion("INIT_PWD not between", value1, value2, "initPwd");
            return (Criteria) this;
        }

        public Criteria andLogintotalIsNull() {
            addCriterion("LOGINTOTAL is null");
            return (Criteria) this;
        }

        public Criteria andLogintotalIsNotNull() {
            addCriterion("LOGINTOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andLogintotalEqualTo(BigDecimal value) {
            addCriterion("LOGINTOTAL =", value, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalNotEqualTo(BigDecimal value) {
            addCriterion("LOGINTOTAL <>", value, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalGreaterThan(BigDecimal value) {
            addCriterion("LOGINTOTAL >", value, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOGINTOTAL >=", value, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalLessThan(BigDecimal value) {
            addCriterion("LOGINTOTAL <", value, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOGINTOTAL <=", value, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalIn(List<BigDecimal> values) {
            addCriterion("LOGINTOTAL in", values, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalNotIn(List<BigDecimal> values) {
            addCriterion("LOGINTOTAL not in", values, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOGINTOTAL between", value1, value2, "logintotal");
            return (Criteria) this;
        }

        public Criteria andLogintotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOGINTOTAL not between", value1, value2, "logintotal");
            return (Criteria) this;
        }

        public Criteria andPasswdExpIsNull() {
            addCriterion("PASSWD_EXP is null");
            return (Criteria) this;
        }

        public Criteria andPasswdExpIsNotNull() {
            addCriterion("PASSWD_EXP is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdExpEqualTo(String value) {
            addCriterion("PASSWD_EXP =", value, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpNotEqualTo(String value) {
            addCriterion("PASSWD_EXP <>", value, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpGreaterThan(String value) {
            addCriterion("PASSWD_EXP >", value, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWD_EXP >=", value, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpLessThan(String value) {
            addCriterion("PASSWD_EXP <", value, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpLessThanOrEqualTo(String value) {
            addCriterion("PASSWD_EXP <=", value, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpLike(String value) {
            addCriterion("PASSWD_EXP like", value, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpNotLike(String value) {
            addCriterion("PASSWD_EXP not like", value, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpIn(List<String> values) {
            addCriterion("PASSWD_EXP in", values, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpNotIn(List<String> values) {
            addCriterion("PASSWD_EXP not in", values, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpBetween(String value1, String value2) {
            addCriterion("PASSWD_EXP between", value1, value2, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andPasswdExpNotBetween(String value1, String value2) {
            addCriterion("PASSWD_EXP not between", value1, value2, "passwdExp");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("MOBILE =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("MOBILE >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("MOBILE <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("MOBILE like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("MOBILE not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("MOBILE in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("MOBILE not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("DEPARTMENT is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("DEPARTMENT is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("DEPARTMENT =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("DEPARTMENT <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("DEPARTMENT >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("DEPARTMENT >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("DEPARTMENT <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("DEPARTMENT <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("DEPARTMENT like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("DEPARTMENT not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("DEPARTMENT in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("DEPARTMENT not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("DEPARTMENT between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("DEPARTMENT not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andSpButtonIsNull() {
            addCriterion("SP_BUTTON is null");
            return (Criteria) this;
        }

        public Criteria andSpButtonIsNotNull() {
            addCriterion("SP_BUTTON is not null");
            return (Criteria) this;
        }

        public Criteria andSpButtonEqualTo(String value) {
            addCriterion("SP_BUTTON =", value, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonNotEqualTo(String value) {
            addCriterion("SP_BUTTON <>", value, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonGreaterThan(String value) {
            addCriterion("SP_BUTTON >", value, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonGreaterThanOrEqualTo(String value) {
            addCriterion("SP_BUTTON >=", value, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonLessThan(String value) {
            addCriterion("SP_BUTTON <", value, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonLessThanOrEqualTo(String value) {
            addCriterion("SP_BUTTON <=", value, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonLike(String value) {
            addCriterion("SP_BUTTON like", value, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonNotLike(String value) {
            addCriterion("SP_BUTTON not like", value, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonIn(List<String> values) {
            addCriterion("SP_BUTTON in", values, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonNotIn(List<String> values) {
            addCriterion("SP_BUTTON not in", values, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonBetween(String value1, String value2) {
            addCriterion("SP_BUTTON between", value1, value2, "spButton");
            return (Criteria) this;
        }

        public Criteria andSpButtonNotBetween(String value1, String value2) {
            addCriterion("SP_BUTTON not between", value1, value2, "spButton");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeIsNull() {
            addCriterion("PASSWD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeIsNotNull() {
            addCriterion("PASSWD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeEqualTo(String value) {
            addCriterion("PASSWD_TYPE =", value, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeNotEqualTo(String value) {
            addCriterion("PASSWD_TYPE <>", value, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeGreaterThan(String value) {
            addCriterion("PASSWD_TYPE >", value, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWD_TYPE >=", value, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeLessThan(String value) {
            addCriterion("PASSWD_TYPE <", value, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeLessThanOrEqualTo(String value) {
            addCriterion("PASSWD_TYPE <=", value, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeLike(String value) {
            addCriterion("PASSWD_TYPE like", value, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeNotLike(String value) {
            addCriterion("PASSWD_TYPE not like", value, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeIn(List<String> values) {
            addCriterion("PASSWD_TYPE in", values, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeNotIn(List<String> values) {
            addCriterion("PASSWD_TYPE not in", values, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeBetween(String value1, String value2) {
            addCriterion("PASSWD_TYPE between", value1, value2, "passwdType");
            return (Criteria) this;
        }

        public Criteria andPasswdTypeNotBetween(String value1, String value2) {
            addCriterion("PASSWD_TYPE not between", value1, value2, "passwdType");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(String value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(String value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(String value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(String value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLike(String value) {
            addCriterion("UPDATE_DATE like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotLike(String value) {
            addCriterion("UPDATE_DATE not like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<String> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<String> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andExpDateIsNull() {
            addCriterion("EXP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpDateIsNotNull() {
            addCriterion("EXP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpDateEqualTo(String value) {
            addCriterion("EXP_DATE =", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotEqualTo(String value) {
            addCriterion("EXP_DATE <>", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateGreaterThan(String value) {
            addCriterion("EXP_DATE >", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateGreaterThanOrEqualTo(String value) {
            addCriterion("EXP_DATE >=", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLessThan(String value) {
            addCriterion("EXP_DATE <", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLessThanOrEqualTo(String value) {
            addCriterion("EXP_DATE <=", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLike(String value) {
            addCriterion("EXP_DATE like", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotLike(String value) {
            addCriterion("EXP_DATE not like", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateIn(List<String> values) {
            addCriterion("EXP_DATE in", values, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotIn(List<String> values) {
            addCriterion("EXP_DATE not in", values, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateBetween(String value1, String value2) {
            addCriterion("EXP_DATE between", value1, value2, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotBetween(String value1, String value2) {
            addCriterion("EXP_DATE not between", value1, value2, "expDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_user
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 10 17:00:22 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_user
     *
     * @mbggenerated Thu Sep 10 17:00:22 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}